modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="arcanecraft"
version="1.16.5-r1.0"
displayName="ArcaneCraft II"
credits="Credits are on mod's page."
displayURL="https://github.com/Max094Reikeb/ArcaneCraft-II"
authors="Max094_Reikeb"
description='''
ArcaneCraft 2 is the recreation of ArcaneCraft.
'''

[[dependencies.arcanecraft]] #optional
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.arcanecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
